// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_d11QZ5usbDzb_k9ItrvHCuQf6jvggQ',
    appId: '1:55330843004:web:22aea0223362b6c2981cf9',
    messagingSenderId: '55330843004',
    projectId: 'travel-planning-app-cc152',
    authDomain: 'travel-planning-app-cc152.firebaseapp.com',
    storageBucket: 'travel-planning-app-cc152.firebasestorage.app',
    measurementId: 'G-QGVKF6V7QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfLWDAyTB1aieoRi3u8DcFXrSfVHXGNhg',
    appId: '1:55330843004:android:eefc46c84f86407c981cf9',
    messagingSenderId: '55330843004',
    projectId: 'travel-planning-app-cc152',
    storageBucket: 'travel-planning-app-cc152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnhO_cWI6V5LqFN17TFq2qMPnYJjmd8_8',
    appId: '1:55330843004:ios:d8ed82a48daf78b5981cf9',
    messagingSenderId: '55330843004',
    projectId: 'travel-planning-app-cc152',
    storageBucket: 'travel-planning-app-cc152.firebasestorage.app',
    iosBundleId: 'com.example.lakbayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnhO_cWI6V5LqFN17TFq2qMPnYJjmd8_8',
    appId: '1:55330843004:ios:d8ed82a48daf78b5981cf9',
    messagingSenderId: '55330843004',
    projectId: 'travel-planning-app-cc152',
    storageBucket: 'travel-planning-app-cc152.firebasestorage.app',
    iosBundleId: 'com.example.lakbayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT_d11QZ5usbDzb_k9ItrvHCuQf6jvggQ',
    appId: '1:55330843004:web:097bd087211445d9981cf9',
    messagingSenderId: '55330843004',
    projectId: 'travel-planning-app-cc152',
    authDomain: 'travel-planning-app-cc152.firebaseapp.com',
    storageBucket: 'travel-planning-app-cc152.firebasestorage.app',
    measurementId: 'G-X6EQYXHLZ5',
  );
}
